from urls_src.links import Links


class PCHLinks(Links):

    def __init__(self, args):
        params = {}
        params['domain'] = "https://www.pch.net/resources"
        params['collectors'] = ['route-collector.abj.pch.net',
                                'route-collector.acc.pch.net',
                                'route-collector.akl.pch.net',
                                'route-collector.ams.pch.net',
                                'route-collector.amsix-lga.pch.net',
                                'route-collector.amsix-ord.pch.net',
                                'route-collector.amsix-sfo.pch.net',
                                'route-collector.any.pch.net',
                                'route-collector.ari.pch.net',
                                'route-collector.ark.pch.net',
                                'route-collector.asu.pch.net',
                                'route-collector.atl.pch.net',
                                'route-collector.bah.pch.net',
                                'route-collector.bcn.pch.net',
                                'route-collector.beg.pch.net',
                                'route-collector.ber.pch.net',
                                'route-collector.bey.pch.net',
                                'route-collector.bgr.pch.net',
                                'route-collector.bjl.pch.net',
                                'route-collector.bjm.pch.net',
                                'route-collector.bkk.pch.net',
                                'route-collector.blz.pch.net',
                                'route-collector.bom.pch.net',
                                'route-collector.bos.pch.net',
                                'route-collector.bru.pch.net',
                                'route-collector.bur.pch.net',
                                'route-collector.bvy.pch.net',
                                'route-collector.bwi.pch.net',
                                'route-collector.bze.pch.net',
                                'route-collector.cai.pch.net',
                                'route-collector.cdg.pch.net',
                                'route-collector.chix.pch.net',
                                'route-collector.cmb.pch.net',
                                'route-collector.coo.pch.net',
                                'route-collector.cor.pch.net',
                                'route-collector.cpt.pch.net',
                                'route-collector.dac.pch.net',
                                'route-collector.dar.pch.net',
                                'route-collector.decix-dus.fra.pch.net',
                                'route-collector.decix-ham.fra.pch.net',
                                'route-collector.decix-muc.fra.pch.net',
                                'route-collector.decix-ny.pch.net',
                                'route-collector.den.pch.net',
                                'route-collector.dfw.pch.net',
                                'route-collector.dkr.pch.net',
                                'route-collector.dom.pch.net',
                                'route-collector.dub.pch.net',
                                'route-collector.dur.pch.net',
                                'route-collector.dxb.pch.net',
                                'route-collector.ecix-ber.pch.net',
                                'route-collector.ecix-dus.pch.net',
                                'route-collector.ecix-fra.pch.net',
                                'route-collector.ecix-ham.pch.net',
                                'route-collector.ecix-muc.pch.net',
                                'route-collector.edi.pch.net',
                                'route-collector.equinix-dallas.pch.net',
                                'route-collector.equinix-paris.pch.net',
                                'route-collector.equinix-sg.pch.net',
                                'route-collector.espanix-mad.pch.net',
                                'route-collector.evn.pch.net',
                                'route-collector.ewr.pch.net',
                                'route-collector.eze.pch.net',
                                'route-collector.fih.pch.net',
                                'route-collector.fra.pch.net',
                                'route-collector.franceix-mrs.pch.net',
                                'route-collector.gbe.pch.net',
                                'route-collector.gnd.pch.net',
                                'route-collector.gye.pch.net',
                                'route-collector.gza.pch.net',
                                'route-collector.hkg.pch.net',
                                'route-collector.hre.pch.net',
                                'route-collector.iad.pch.net',
                                'route-collector.icn.pch.net',
                                'route-collector.ist.pch.net',
                                'route-collector.jax.pch.net',
                                'route-collector.jhb.pch.net',
                                'route-collector.jkt.pch.net',
                                'route-collector.jnb.pch.net',
                                'route-collector.jpix.pch.net',
                                'route-collector.kbp.pch.net',
                                'route-collector.kgl.pch.net',
                                'route-collector.kin.pch.net',
                                'route-collector.kla.pch.net',
                                'route-collector.klu.pch.net',
                                'route-collector.krt.pch.net',
                                'route-collector.ktm.pch.net',
                                'route-collector.kul.pch.net',
                                'route-collector.kye.pch.net',
                                'route-collector.lad.pch.net',
                                'route-collector.lax.pch.net',
                                'route-collector.lba.pch.net',
                                'route-collector.lbv.pch.net',
                                'route-collector.lfw.pch.net',
                                'route-collector.lga.pch.net',
                                'route-collector.lhr.pch.net',
                                'route-collector.linx-iad.pch.net',
                                'route-collector.lis.pch.net',
                                'route-collector.lonap.pch.net',
                                'route-collector.los.pch.net',
                                'route-collector.lpb.pch.net',
                                'route-collector.lys.pch.net',
                                'route-collector.mad.pch.net',
                                'route-collector.man.pch.net',
                                'route-collector.mba.pch.net',
                                'route-collector.mci.pch.net',
                                'route-collector.mcix.pch.net',
                                'route-collector.megaport-akl.pch.net',
                                'route-collector.megaport-bne.pch.net',
                                'route-collector.megaport-bur.pch.net',
                                'route-collector.megaport-mel.pch.net',
                                'route-collector.megaport-per.pch.net',
                                'route-collector.megaport-qpg.pch.net',
                                'route-collector.megaport-sea.pch.net',
                                'route-collector.megaport-syd.pch.net',
                                'route-collector.megaport-yyz.pch.net',
                                'route-collector.mex.pch.net',
                                'route-collector.mgm.pch.net',
                                'route-collector.mgq.pch.net',
                                'route-collector.mia.pch.net',
                                'route-collector.midwestix-chicago.pch.net',
                                'route-collector.mke.pch.net',
                                'route-collector.mnl.pch.net',
                                'route-collector.mpm.pch.net',
                                'route-collector.mrs.pch.net',
                                'route-collector.mru.pch.net',
                                'route-collector.muc.pch.net',
                                'route-collector.napafrica-jnb.pch.net',
                                'route-collector.nbe.pch.net',
                                'route-collector.nbo.pch.net',
                                'route-collector.ndd.pch.net',
                                'route-collector.netix.pch.net',
                                'route-collector.nl-ix.pch.net',
                                'route-collector.nlv.pch.net',
                                'route-collector.nqn.pch.net',
                                'route-collector.nrt.pch.net',
                                'route-collector.nsw-ix.pch.net',
                                'route-collector.nyiix.pch.net',
                                'route-collector.ord.pch.net',
                                'route-collector.otp.pch.net',
                                'route-collector.paix-sea.pch.net',
                                'route-collector.pao.pch.net',
                                'route-collector.pap.pch.net',
                                'route-collector.pbh.pch.net',
                                'route-collector.pcb.pch.net',
                                'route-collector.pdx.pch.net',
                                'route-collector.per.pch.net',
                                'route-collector.phx.pch.net',
                                'route-collector.pnh.pch.net',
                                'route-collector.pos.pch.net',
                                'route-collector.prg.pch.net',
                                'route-collector.pss.pch.net',
                                'route-collector.qls.pch.net',
                                'route-collector.qpg.pch.net',
                                'route-collector.ric.pch.net',
                                'route-collector.rix-ams.pch.net',
                                'route-collector.rno.pch.net',
                                'route-collector.rob.pch.net',
                                'route-collector.ros.pch.net',
                                'route-collector.scl.pch.net',
                                'route-collector.sdb.pch.net',
                                'route-collector.sea.pch.net',
                                'route-collector.sfinx.pch.net',
                                'route-collector.sfo.pch.net',
                                'route-collector.sge.pch.net',
                                'route-collector.sgu.pch.net',
                                'route-collector.sgw.pch.net',
                                'route-collector.sin.pch.net',
                                'route-collector.sjo.pch.net',
                                'route-collector.slu.pch.net',
                                'route-collector.sna.pch.net',
                                'route-collector.sof.pch.net',
                                'route-collector.stl.pch.net',
                                'route-collector.syd.pch.net',
                                'route-collector.szg.pch.net',
                                'route-collector.tcix.pch.net',
                                'route-collector.teraco-dur.pch.net',
                                'route-collector.tgu.pch.net',
                                'route-collector.tie-ny.pch.net',
                                'route-collector.tie-phx.pch.net',
                                'route-collector.tll.pch.net',
                                'route-collector.tlv.pch.net',
                                'route-collector.tmp.pch.net',
                                'route-collector.tnr.pch.net',
                                'route-collector.tpa.pch.net',
                                'route-collector.trn.pch.net',
                                'route-collector.tun.pch.net',
                                'route-collector.unitedix.pch.net',
                                'route-collector.vie.pch.net',
                                'route-collector.vli.pch.net',
                                'route-collector.vno.pch.net',
                                'route-collector.waw.pch.net',
                                'route-collector.wdh.pch.net',
                                'route-collector.wlg.pch.net',
                                'route-collector.wpgix.pch.net',
                                'route-collector.yhz.pch.net',
                                'route-collector.yow.pch.net',
                                'route-collector.yqm.pch.net',
                                'route-collector.yul.pch.net',
                                'route-collector.ywg.pch.net',
                                'route-collector.yxe.pch.net',
                                'route-collector.yyc.pch.net',
                                'route-collector.yyz.pch.net',
                                'route-collector.zrh.pch.net']

        params['rib_prefix'] = None
        params['update_prefix'] = None

        params['rib_instances'] = ['day']
        params['update_instances'] = [str(x).zfill(2)
                                      + '-'
                                      + str(y).zfill(2)
                                      for x in range(24)
                                      for y in range(60)]

        params['file_extension'] = 'gz'
        params['filename_format'] = None

        params['ribs_path'] = ['f"{domain}/Routing_Data/IPv4_daily_snapshots/{year}/{month}/{collector}/'
                               '{collector}-ipv4_bgp_routes.{year}.{month}.{eval(instance)}.{file_extension}"',
                               'f"{domain}/Routing_Data/IPv6_daily_snapshots/{year}/{month}/{collector}/'
                               '{collector}-ipv6_bgp_routes.{year}.{month}.{eval(instance)}.{file_extension}"']

        params['updates_path'] = ['f"{domain}/Raw_Routing_Data/{collector}/{year}/{month}/{day}/'
                                  '{collector}-mrt-bgp-updates-{year}-{month}-{day}-{instance}.{file_extension}"']

        params['url_format'] = None

        Links.__init__(self,
                       args,
                       params)
